# Generated by Django 2.2.5 on 2019-09-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='search_name',
            new_name='name',
        ),
    ]
