# Generated by Django 2.2.5 on 2019-09-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20190923_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
