# Generated by Django 2.2.5 on 2019-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_todolist_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='ip_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
